name: ifarchive-testframe

services:
  ifarch:
    build: .
    ports:
      - 8888:80
    volumes:
      - ./ifarchive-static/index.html:/var/ifarchive/htdocs/index.html
      - ./ifarchive-static/misc:/var/ifarchive/htdocs/misc
      - ./ifarchive-ifmap-py/make-master-index:/var/ifarchive/bin/make-master-index
      - ./ifarchive-ifmap-py/make-master-index.py:/var/ifarchive/bin/make-master-index.py
      - ./ifarchive-ifmap-py/build-indexes:/var/ifarchive/bin/build-indexes
      - ./ifarchive-ifmap-py/build-indexes-bg:/var/ifarchive/bin/build-indexes-bg
      # for ifmap
      - ./ifarchive-ifmap-py/ifmap.py:/var/ifarchive/bin/ifmap.py
      - ./ifarchive-ifmap-py/lib:/var/ifarchive/lib/ifmap
      # for upload
      - ./ifarchive-upload-py/upload.py:/var/ifarchive/cgi-bin/upload.py
      - ./ifarchive-upload-py/lib:/var/ifarchive/lib/uploader
      # for admintool
      - ./ifarchive-admintool/admin.wsgi:/var/ifarchive/wsgi-bin/admin.wsgi
      - ./ifarchive-admintool/tinyapp:/var/ifarchive/wsgi-bin/tinyapp
      - ./ifarchive-admintool/adminlib:/var/ifarchive/wsgi-bin/adminlib
      - ./ifarchive-admintool/templates:/var/ifarchive/lib/admintool
      # for search
      - ./ifarchive-search/search.wsgi:/var/ifarchive/wsgi-bin/search.wsgi
      - ./ifarchive-search/searchlib:/var/ifarchive/wsgi-bin/searchlib
      - ./ifarchive-search/templates:/var/ifarchive/lib/searchtpl
