name: ifarchive-testframe

services:
  ifarch:
    build: .
    ports:
      - 8888:80
    volumes:
      - ./ifarchive-ifmap-py/lib:/var/ifarchive/lib/ifmap
      - ./ifarchive-upload-py/lib:/var/ifarchive/lib/uploader
